#!/bin/bash
clear
wmctrl -r :ACTIVE: -N "Applying Build Settings"
now=$(date +"%T")
echo "Current time : $now"
echo "Applying Build Settings"
sleep 1

#CONFIGS
echo "Setting ARM Arch"
export ARCH=arm
echo "Setting ARM SUBARCH"
export SUBARCH=arm
echo "Setting Defconfig"
export DEFCONFIG=bidji_find5_defconfig
echo "Setting Date And Time For Zip File"
sleep 1
export NOW=$(date +"%m-%d-%y_%H:%M")
sleep 1

#Build
echo "Cleaning Up Previous Build"
sleep 1
make clean && make mrproper
wmctrl -r :ACTIVE: -N "Starting Build Process"
if [ -f .config ];
then
   echo ".config exists"
   echo "Continuing To Compiler"
   sleep 1
else
   echo ".config Does Not Exists"
   echo "Compiling From $TOOLCHAIN $DEFCONFIG"
   echo "Setting GCC"
   export CROSS_COMPILE=/home/gamakireta/android/toolchains/arm-cortex_a15-linux-gnueabihf-linaro_4.9.4-2015.06/bin/arm-cortex_a15-linux-gnueabihf-
   sleep 1
   echo "Create Config"
   make ARCH=$ARCH $DEFCONFIG
   sleep 1
fi
echo "Starting Build Process"
sleep 1
make -j8

if [ -f $ZIMAGE ];
then
   echo "$ZIMAGE exists"
   echo "Compile Complete Continuing To Stripping"
   sleep 1
else
   echo "$ZIMAGE Does Not Exists Please Check For Compile Errors"
   echo "Now exiting script"
   sleep 1
   exit 0
fi

#Bidji repackage
wmctrl -r :ACTIVE: -N "BIDJI Kernel Flash Packaging"
echo "Starting Packing To Recovery Flashable AnyKernel Zip and boot.img"
cd AnyKernel/
echo "Removing Old Files"
rm -rf kernel/zImage
cd ..
rm -rf zImage
rm -rf boot.img
rm -rf ramdisk.cpio.gz
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Copying zImage"
find 'arch/' -name "zImage" -exec cp -av {} AnyKernel/kernel/ \;
find 'arch/' -name "zImage" -exec cp -av {} . \;
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Creating boot.img"
cd ramdisk/
find . | cpio -o -H newc | gzip > ../ramdisk.cpio.gz
cd ..
mkbootimg --kernel zImage --ramdisk ramdisk.cpio.gz --base 0x80200000 --pagesize 2048 --ramdiskaddr 0x82200000 --cmdline 'console=ttyHSL0,115200,n8 androidboot.hardware=qcom lpj=67677 user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 zcache' -o boot.img
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Repackage bidji-find5-AnyKernel-v.-"$NOW".zip"
cd AnyKernel/
zip -r bidji-find5-AnyKernel-v.-"$NOW".zip kernel/ META-INF/
sleep 1
echo "===============================================Done========================================"
echo "Signing Zip for AnyKernel"
java -classpath testsign.jar testsign bidji-find5-AnyKernel-v.-"$NOW".zip bidji-find5-AnyKernel-v.-"$NOW"-Signed.zip
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Moving out to Released Folder"
mv bidji-find5-AnyKernel-v.-"$NOW"-Signed.zip ../../outputs/bidji-find5-AnyKernel-v.-"$NOW".zip
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Repackage bidji-find5-v.-"$NOW".zip"
cd ..
zip -r bidji-find5-v."$NOW".zip boot.img META-INF/
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Signing Zip for Flashable"
java -classpath testsign.jar testsign bidji-find5-v."$NOW".zip bidji-find5-v."$NOW"-Signed.zip
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Moving out to Released Folder"
mv bidji-find5-v."$NOW"-Signed.zip ../outputs/bidji-find5-v."$NOW".zip
sleep 1
echo "===============================================Done========================================"
sleep 1
echo "Finished Compiling and Repackaging Anykernel"
wmctrl -r :ACTIVE: -N "Terminal"
nowf=$(date)
echo "Completion Time : $nowf"
